spring:
  application:
    name: crmdemo

  datasource:
    url: ${SQL_URL}
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mongodb:
    uri: ${MONGODB_URI}
security:
  super-admin:
    name: ${SUPER_ADMIN_NAME}
    email: ${SUPER_ADMIN_EMAIL}
    phone: ${SUPER_ADMIN_PHONE}
    password: ${SUPER_ADMIN_PASSWORD}

  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 3600000